import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ClientLayout from "@/components/ClientLayout";
import { Toaster } from "react-hot-toast";
import { StateContextProvider } from "@/context/StateContextProvider";

const outfit = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <StateContextProvider>
        <html lang="en">
          <body className={`${outfit.variable} antialiased`}>
            <ClientLayout>{children}</ClientLayout>
          </body>
        </html>
      </StateContextProvider>
    </ClerkProvider>
  );
}
